config/routes.rb
Rails.application.routes.draw do
  
  resources :crews
  resources :groups
  resources :concerts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :Group
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :Group
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :concerts, dependent: :destroy
    validates :name, presence: true
    validates :debut_date, presence: true
    validates :number_of_members, presence: true
    validates :type_of_band, presence: true
    has_many :crews, dependent: :destroy
    
    enum type_of_band: [:Men, :Women, :Band]

    def number_of_concert
        Concert.where(Group_id: id).count
    end

    def total_number_of_people
        self.concerts.pluck(:number_of_people).sum
    end

    def concerts_this_month
        @concerts = Concert.where(Group_id: id)
        concerts_month = []
        @concerts.each do |concert|
            if concert.concert_date > Time.now.beginning_of_month && concert.concert_date < Time.now.end_of_month
                concerts_month.push(concert.concert_date)
            end
        end
        if concerts_month.any?
            concerts_month.count
        else
            "Don't have concerts this month"
        end
    end

    def the_last_concert
        if self.concerts.count > 0
            self.concerts.order(concert_date: :asc).last.concert_date
        else
            "no debut"
        end
    end  

    def amount_of_public
        self.concerts.pluck(:number_of_people).max
    end

    def concert_duration
        self.concerts.pluck(:duration).max
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:concert_name, :concert_date, :number_of_people, :duration, :Group_id)
    end
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: %i[ show edit update destroy ]

  # GET /crews or /crews.json
  def index
    @crews = Crew.all
  end

  # GET /crews/1 or /crews/1.json
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews or /crews.json
  def create
    @crew = Crew.new(crew_params)

    respond_to do |format|
      if @crew.save
        format.html { redirect_to @crew, notice: "Crew was successfully created." }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1 or /crews/1.json
  def update
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to @crew, notice: "Crew was successfully updated." }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1 or /crews/1.json
  def destroy
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to crews_url, notice: "Crew was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(:name, :Group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :debut_date, :number_of_members, :type_of_band)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :concert_name %>
    <%= form.text_field :concert_name %>
  </div>

  <div class="field">
    <%= form.label :concert_date %>
    <%= form.date_select :concert_date %>
  </div>

  <div class="field">
    <%= form.label :number_of_people %>
    <%= form.number_field :number_of_people %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :Group_id %>
    <%= form.text_field :Group_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table>
  <thead>
    <tr>
      <th>Concert name</th>
      <th>Concert date</th>
      <th>Number of people</th>
      <th>Duration</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.concert_name %></td>
        <td><%= concert.concert_date %></td>
        <td><%= concert.number_of_people %></td>
        <td><%= concert.duration %></td>
        <td><%= concert.Group_id %></td>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Concert name:</strong>
  <%= @concert.concert_name %>
</p>

<p>
  <strong>Concert date:</strong>
  <%= @concert.concert_date %>
</p>

<p>
  <strong>Number of people:</strong>
  <%= @concert.number_of_people %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @concert.duration %>
</p>

<p>
  <strong>Group:</strong>
  <%= @concert.Group_id %>
</p>

<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/crews/_form.html.erb
<%= form_with(model: crew, local: true) do |form| %>
  <% if crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
        <% crew.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Group_id %>
    <%= form.text_field :Group_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

app/views/crews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.name %></td>
        <td><%= crew.Group_id %></td>
        <td><%= link_to 'Show', crew %></td>
        <td><%= link_to 'Edit', edit_crew_path(crew) %></td>
        <td><%= link_to 'Destroy', crew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crew', new_crew_path %>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Back', crews_path %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crew.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @crew.Group_id %>
</p>

<%= link_to 'Edit', edit_crew_path(@crew) %> |
<%= link_to 'Back', crews_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :debut_date %>
    <%= form.date_select :debut_date %>
  </div>

  <div class="field">
    <%= form.label :number_of_members %>
    <%= form.number_field :number_of_members %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :type_of_band, Group.type_of_bands.keys %>
    </div>
  
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Debut date</th>
      <th>Number of members</th>
      <th>Type</th>
      <th>Members</th>
      <th>Number of concert</th>
      <th>Total number of people</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.debut_date %></td>
        <td><%= group.number_of_members %></td>
        <td><%= group.type_of_band %></td>
        <td>
          <% group.crews.each do |p| %>  
            <ul>
              <li>
                <%= p.name %>
              </li>
            </ul>
            
          <%end%>

        </td>
        <td><%= group.number_of_concert %></td>
        <td><%= group.total_number_of_people %></td>

        
        
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>
<%= link_to 'New Crew', new_crew_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Debut date:</strong>
  <%= @group.debut_date %>
</p>

<p>
  <strong>Number of members:</strong>
  <%= @group.number_of_members %>
</p>

<p>
  <strong>Type:</strong>
  <%= @group.type_of_band %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

<table>
  <h3>Data</h3>
  <tr>
    <td>Concerts this month </td>
    <td><%= @group.concerts_this_month %></td>
  </tr>
  <tr>
    <td>The last concert </td>
    <% if @group.the_last_concert != "no debut" %>
      <td><%= @group.the_last_concert.strftime("%Y-%B-%A") %></td>
    <% end %>
  </tr>
  <tr>
    <td>Greater amount of public </td>
    <td><%= @group.amount_of_public %></td>
  </tr>
  <tr>
    <td>Longer concert duration </td>
    <td><%= @group.concert_duration %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventProducer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>